### ISSUE TITLE
Not detecting any spikes on GPU cluster

### ISSUE THREAD

**Issue by sjvenditto** [catalystneuro/brody-lab-to-nwb#20]
Hello,

I've been testing out the SpikeInterface pipeline for 2.0 probes -- I followed the steps you all went through during the 10/7/21 meeting to get everything installed, and added in the line to filter and downsample recording_lf from recording_ap. However, when it's sent to MATLAB to run kilosort2, it doesn't detect any spikes from the preprocessed data. I've run this session through kilosort2 outside of SpikeInterface, and I know this isn't the case. A thought we had was whatever pre-processing is being done through SpikeInterface is incorrectly reading the SpikeGLX metadata, since the metadata structure for 2.0 probes is slightly different from 1.0 probes. 

I've included a zip folder containing the cluster output/error stack (slurm-7949799.out), the SLURM script to submit the job (spikeinterface_job.slurm), the python script from brody-lab-to-nwb that I used to run SpikeInterface (spikeglx_spikeinterface_pipeline.py), and the metadata from one of my 2.0 probes in case the differing file structure is contributing to the issue (M136_2021_12_08_rig204_g0_t0.imec0.ap.meta)

Thanks!
Sarah Jo

[SpikeInterface_GPUclusterError.zip](https://github.com/catalystneuro/brody-lab-to-nwb/files/7989638/SpikeInterface_GPUclusterError.zip)

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Any ideas? Should we just suggest an update to the new API and see if the issue is reproduced there?

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Is likely quite busy right at the moment as they are preparing for a new SpikeInterface release tomorrow.

First question, when you say "2.0 probe" is this the same as "Neuropixels 2.0" format? If so I think there is a different extractor altogether for that, probably only available in the new interface: @alejoe91 do you know have a link to that?

In the meantime I took a look at what I could based on those error message and the issue seems like it might come up well before we reach the sorting stage (though hard to be 100% sure without the `ap.bin`).

It appears it could be a problem with the way the converison to microvolts is done; if we look at the metafile you've attached in the in the [SpikeInterface_GPUclusterError.zip](https://github.com/catalystneuro/brody-lab-to-nwb/files/7989638/SpikeInterface_GPUclusterError.zip) file, and compare the fields related to ap channel gains, we find they are all zero in the case of your meta file, whereas other SpikeGLX files we've worked with have a non-zero value there.

To reproduce in isolation
```python
from pathlib import Path

from spikeextractors.extractors.spikeglxrecordingextractor.spikeglxrecordingextractor import readMeta

M136_meta= readMeta(Path("E:/Brody/Issues/M136_2021_12_08_rig204_g0_t0.imec0.ap.meta"))
M136_ap_gains = [x.split(sep=" ")[3] for x in standard_meta['imroTbl'].split(sep=")") if len(x.split(sep=" ")) >= 3]

standard_meta= readMeta(Path("E:/Brody/Chronic Rat Neuropixels (Poisson Clicks Task)/A242_2019_05_30/Raw/2019-05-30_g0/2019-05-30_g0_imec0/2019-05-30_g0_t0.imec0.ap.meta"))
standard_ap_gains = [x.split(sep=" ")[3] for x in standard_meta['imroTbl'].split(sep=")") if len(x.split(sep=" ")) >= 3]
```

gives

![image](https://user-images.githubusercontent.com/51133164/152367655-e0ef0143-caef-4165-b336-6d0f95b10bad.png)

Actual extraction is done in a less hacky way than this, but these are the elements used in line: https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/spikeglxrecordingextractor/readSGLX.py#L222

Now, I would have thought that spike sorting might have been done on raw traces anyhow, but perhaps the gains were invoked at some point during pre-processing and that corrupted the traces after that point, so that they were all `0` or `np.nan` prior to entering the sorter? @alejoe91 Would know more about that

**Comment by alejoe91** [comment]
Hi guys! Yes I think that the new release will solve it. We will provide very soon a new notebook that uses the new SI API, which is much more efficient than the old one. Also NP2 should be already working out of the box with the new API, but it would be great if you could upload a full recording on the shared drive so we can make sure that it does!

Will keep you updated!

**Comment by CodyCBakerPhD** [comment]
@agbondy @sjvenditto In the meantime, an intermediate fix just to keep you going for now, could be to hard-code the gains to the true value (if you know it) after initializing the RecordingExtractor. That is, in your attached script,

```python
recording_ap = se.SpikeGLXRecordingExtractor(ap_bin_path)
# recording_lf = se.SpikeGLXRecordingExtractor(lf_bin_path)

recording_lf = st.preprocessing.bandpass_filter(recording_ap, freq_min=1, freq_max = 1000)
recording_lf = st.preprocessing.resample(recording_lf, 2500)


if stub_test:
    print("Stub test! Clipping recordings!")
    recording_ap = se.SubRecordingExtractor(recording_ap,
                                            end_frame=int(nsec_stub * recording_ap.get_sampling_frequency()))
    recording_lf = se.SubRecordingExtractor(recording_lf,
                                            end_frame=int(nsec_stub * recording_lf.get_sampling_frequency()))

recordding_ap.set_channel_gains(gains=proper_scalar_gain_value)
# recording_lf.set_channel_gains(gains=proper_scalar_gain_value)
```

That would at least resolve that one particular issue; no guarantees it wouldn't run into any others, but might be worth a try.

You can and should check that the traces of the object look OK after that point, since that is likely what caused the issue in the first place prior to it reaching the spike sorting level.

**Comment by agbondy** [comment]
@alejoe91 I uploaded a recent rat Neuropixels 2.0 recording to the shared Google Drive: https://drive.google.com/drive/u/2/folders/1DWxAIMAlDJVxMKQyLMiyWCnX0v7Qi9uy

There are two folders there. One is a mouse recording that Manuel uploading some time ago. The more recent one is the one I just added, which is a useful additional example because two probe were recorded simultaneously. I don't know how the API handles that currently.

**Comment by agbondy** [comment]
@CodyCBakerPhD Depending on the timeframe of the new SI release, we may try what you suggest. Thanks.

**Comment by alejoe91** [comment]
> @CodyCBakerPhD Depending on the timeframe of the new SI release, we may try what you suggest. Thanks.

We will release today, but the pipeline will require some modifications on our side to be compatible with the new release @agbondy

**Comment by agbondy** [comment]
Awesome. Let us know! Great to see such enthusiastic, rapid development of these tools!

**Comment by sjvenditto** [comment]
Sorry for the slow follow up -- I added in the suggested line of code after the stub test and I'm still running into the same error. It seems like the error is coming from readSGLX in the spikeextrators package, which is taking the gain from the meta file regardless of what I set in the spikeinterface pipeline script

**Comment by CodyCBakerPhD** [comment]
@sjvenditto Ah, true that.

(a) To continue harnessing the existing pipeline (which uses `spikeextractors` function calls), we can potentially make use of some existing `utils` functions from the new SpikeInterface.

Could you try using the following lines to load the data via the new SpikeInterface version and see if that works? (will have to `pip install spikeinterface`)

```python
import spikeinterface
from spikeinterface.extractors import SpikeGLXRecordingExtractor

coerced_recording = spikeinterface.old_api_utils.NewToOldRecording(recording=SpikeGLXRecordingExtractor(folder_path="path to folder with NP2 data"))
```

(b) If that still doesn't enable use of the pipeline, @alejoe91 can help provide instructions for how to update all of the function calls to the new version, it's not too much trouble TBH.

**Comment by sjvenditto** [comment]
```
Setting KILOSORT2_PATH environment variable for subprocess calls to: /home/venditto/github/brody-lab-to-nwb/scripts/../../sorters/kilosort2
Traceback (most recent call last):
  File "spikeglx_spikeinterface_pipeline.py", line 61, in <module>
    recording_ap = spikeinterface.old_api_utils.NewToOldRecording(recording=SpikeGLXRecordingExtractor(folder_path=ap_bin_path))
  File "/home/venditto/.conda/envs/spikeinterface/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/spikeglx.py", line 37, in __init__
    NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id, **neo_kwargs)
  File "/home/venditto/.conda/envs/spikeinterface/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 38, in __init__
    stream_id = stream_ids[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Any ideas?

**Comment by alejoe91** [comment]
Hi @sjvenditto 

Can you try to load the object directly from the new API? In case that works out of the box, give us a week or so to push a new pipeline with the new API (which is also a lot faster!).

You can try the following:

From temrinal:
```
>>> pip install --upgrade spikeinterface
```

In the notebook:
```
import spikeinterface.extractors as se

recording = se.read_spikeglx(folder_path="path-to-spikeglx-root-folder", stream_id="imec0.ap")
print(recording)
```

Let me know if that works! I'll put together an updated notebook in the meanwhile :)

**Comment by sjvenditto** [comment]
It looks like it works loading it in:
```
SpikeGLXRecordingExtractor: 384 channels - 1 segments - 30.0kHz - 7376.323s
```
Am I able to use this in place of the existing code for reading in recording_ap? Or is the new API incompatible with other things later in the pipeline?

**Comment by CodyCBakerPhD** [comment]
@sjvenditto Please download and try out the new and improved pipeline and let us know if you run into any more trouble! 

https://github.com/catalystneuro/brody-lab-to-nwb/blob/si_new_np2/notebooks/spikeglx_spikeinterface_pipeline_NEW.ipynb

**Comment by sjvenditto** [comment]
I've copied the lines into a separate script to run on the cluster, and it looks like everything is loading correctly, but I'm getting hung up on the peak detector:
```
SpikeGLXRecordingExtractor: 384 channels - 1 segments - 30.0kHz - 7376.323s
Sampling frequency: 30000.0
Traceback (most recent call last):
  File "/home/venditto/github/brody-lab-to-nwb/scripts/spikeglx_spikeinterface_pipeline_new.py", line 57, in <module>
    peaks = scp.detect_peaks(recording_processed, **job_kwargs)
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sortingcomponents/peak_detection.py", line 227, in detect_peaks
    processor = ChunkRecordingExecutor(recording, func, init_func, init_args,
TypeError: __init__() got an unexpected keyword argument 'chunk_duration'
```

`job_kwargs` is defined the same as in the notebook:
```
job_kwargs = {"n_jobs": 4, "chunk_duration": "1s", "progress_bar": True}
```

**Comment by alejoe91** [comment]
Oups my bad! `chunk_duration` is a new feature that will be available in the next release. You can use instead: `chunk_size=30000`, or you can specify the amount of memory you want to use (e.g. `toral_memory='2G'`). These are used to split the recording in small chunks for parallel processing. Let me know if that's works

**Comment by CodyCBakerPhD** [comment]
@sjvenditto Hey there - did the new notebook run successfully on the new data?

**Comment by sjvenditto** [comment]
Apologies - I've gotten the SI side of things to run, but I ran into a kilosort installation error. I haven't been able to get around to fixing the installation, but I was hoping to get to it in the next week!

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Do we happen to have the kilosort docker working yet?

**Comment by alejoe91** [comment]
@CodyCBakerPhD not yet, but we're on it! Should take  some time though

**Comment by sjvenditto** [comment]
I've got the ks2 installation path worked out, and this is the error I'm running into now:
```
Traceback (most recent call last):
  File "/home/venditto/github/brody-lab-to-nwb/scripts/spikeglx_spikeinterface_pipeline_new.py", line 94, in <module>
    sorting_outputs = ss.run_sorters(
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/launcher.py", line 257, in run_sorters
    _run_one(task_args)
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/launcher.py", line 33, in _run_one
    run_sorter(sorter_name, recording, output_folder=output_folder,
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 67, in run_sorter
    return run_sorter_local(sorter_name, recording, output_folder=output_folder,
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 86, in run_sorter_local
    SorterClass.set_params_to_folder(
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 142, in set_params_to_folder
    raise AttributeError('Bad parameters: ' + str(bad_params))
AttributeError: Bad parameters: ['chunk_mb']
```
I took the parameters from the notebook but un-commented the ks2 parameters:
```
# user-specific parameters
sorter_params = dict(
    kilosort2=dict(car=False, n_jobs_bin=12, chunk_mb=4000),
    #ironclust=dict(filter=True),
    #tridesclous=dict(n_jobs_bin=job_kwargs["n_jobs"]),
    #spykingcircus=dict(filter=True, num_workers=16),
    #herdingspikes=dict(filter=True)
)
```

**Comment by CodyCBakerPhD** [comment]
Looks similar to above issue where this is now `"chunk_duration": "1s"` @alejoe91 is that correct? Or is the sorter-specific param still the same?

**Comment by alejoe91** [comment]
@sjvenditto @CodyCBakerPhD Yes! sorry we forgot to update the parameters in the notebooks o our side. In the new wrapper, you can pass the `total_memory` param (e.g., `total_memory="2G"` will use a total of 2GB RAM - see https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/sorters/kilosort/kilosort.py#L49). You can also check any sorter specifi param with: `ss.get_sorter_params(sorter_name)`

**Comment by sjvenditto** [comment]
Replaced `chunk_mb` with `total_memory`. New error stack:
```
Traceback (most recent call last):
  File "/home/venditto/github/brody-lab-to-nwb/scripts/spikeglx_spikeinterface_pipeline_new.py", line 94, in <module>
    sorting_outputs = ss.run_sorters(
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/launcher.py", line 257, in run_sorters
    _run_one(task_args)
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/launcher.py", line 33, in _run_one
    run_sorter(sorter_name, recording, output_folder=output_folder,
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 67, in run_sorter
    return run_sorter_local(sorter_name, recording, output_folder=output_folder,
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 88, in run_sorter_local
    SorterClass.setup_recording(recording, output_folder, verbose=verbose)
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 171, in setup_recording
    cls._setup_recording(recording, output_folder, sorter_params, verbose)
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/sorters/kilosort2/kilosort2.py", line 130, in _setup_recording
    positions = np.array(recording.get_channel_locations())
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/core/baserecording.py", line 462, in get_channel_locations
    raise Exception('There are no channel locations')
Exception: There are no channel locations
```

**Comment by alejoe91** [comment]
mmm weird! We'll send you an email to organize a call so we can fix it once and for all :)

**Comment by sjvenditto** [comment]
I'm guessing this error stack is from the update to spikeinterface 0.94 -- has this function call been moved/renamed?

```
SpikeGLXRecordingExtractor: 384 channels - 1 segments - 30.0kHz - 7376.323s
Sampling frequency: 30000.0
Traceback (most recent call last):
  File "/home/venditto/github/brody-lab-to-nwb/scripts/spikeglx_spikeinterface_pipeline_new.py", line 57, in <module>
    peaks = scp.detect_peaks(recording_processed, **job_kwargs)
AttributeError: module 'spikeinterface.sortingcomponents' has no attribute 'detect_peaks'
```

**Comment by sjvenditto** [comment]
So the good news is I haven't run into any new errors; the not as good news is the job is timing out after 24 hours. I feel like it shouldn't take that long because running ks2 on our local analysis computer only takes ~2 hours for a single probe/session. I've attached the .out file so you can see where it got interrupted: [slurm-8665194.out.txt](https://github.com/catalystneuro/brody-lab-to-nwb/files/8781112/slurm-8665194.out.txt). It looks like ks2 finished running, but it timed out during the post-processing. My guess is I'm not setting the parallelization parameters correctly on the cluster, but I'll admit that I'm not really sure how to properly set them. Do you have a better intuition on how to set up the job? For reference, the cluster I'm using is TigerGPU, whose specs are listed here: https://researchcomputing.princeton.edu/systems/tiger

Here are the parameters I'm setting for the Slurm job scheduler:
```
#SBATCH --nodes=1                             # node count
#SBATCH --ntasks=1                            # total number of tasks across all nodes
#SBATCH --cpus-per-task=7                     # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=16G                     # memory per cpu-core (4G is default)
#SBATCH --gres=gpu:1                          # number of gpus per node
#SBATCH --time=24:00:00                       # total run time limit (HH:MM:SS)
```
The SpikeInterface parallelization parameters are set at:
```
job_kwargs = {"n_jobs": 4, "chunk_size": 30000, "progress_bar": True}
```
The kilosort2 parameters are:
```
sorter_params = dict(
    kilosort2=dict(car=False, n_jobs_bin=4, total_memory="4G"))
```
I did try running once with `n_jobs_bin=7` and `total_memory="16G"` for the kilosort2 parameters (and everything else the same as above), but that job failed with an out of memory error

**Comment by agbondy** [comment]
@alejoe91 @CodyCBakerPhD Based on the slurm output text file Sarah Jo attached, it looks like ks2 actually did finish in a reasonable amount of time (~4000s or ~1hr) which implies the SpikeInterface stuff is what took most of the time of the job, before it timed out during "Extract Waveforms". Any tips for removing unnecessary computation steps or otherwise speeding things up? A node on our cluster can theoretically use up to 20 cores and has up to 256GB of memory across those cores, but those are not being fully used now it looks like. Each node also has up to 4 GPUs but currently SI doesn't use GPUs is that right?

**Comment by alejoe91** [comment]
Hi @sjvenditto @agbondy 

Inspecting the slurm output, it seems that something weird happened at some point in the waveform extraction: up to line 7733 (~29%) the estimated time is around 1h (`20:13<30:52`, which is fair for 4 jobs), but then suddenly everything seems to slow down and ET quickly increases to over 30h.. I suspect this could be due to filling up the disk space of the node. Does it make any sense? Can you control the disk space allocated to a node? Note that waveform extraction, if you have many units on NP probes, creates quite large files..

Anyways, as a first try, I would start by using `#SBATCH --cpus-per-task=20`, `job_kwargs = {"n_jobs": 20, "chunk_size": 30000, "progress_bar": True}` and `sorter_params = dict(kilosort2=dict(car=False, n_jobs_bin=20, total_memory="500M"))` (in general smaller chunks help with parallelization. 

SI currently doesn't use GPUs, but we'll try little by little to provide GO=PU backends for the main heavy functions.

@sjvenditto let me know if that helps and thank you for sharing the ouput!

**Comment by sjvenditto** [comment]
Sorry for the hiatus --

It looks like the timeout was due to the extracted waveforms being saved to my local directory on TigerGPU instead of to scratch, so my local directory ran out of space. I changed the save location of the waveforms to the scratch space and it ran in a reasonable amount of time (~30 minutes), but now I've run into this error:

```
/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/numpy/lib/function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/numpy/core/_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(
/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/toolkit/qualitymetrics/misc_metrics.py:241: RuntimeWarning: invalid value encountered in true_divide
  violation_rate = num_violations / violation_time
Traceback (most recent call last):
  File "/home/venditto/github/brody-lab-to-nwb/scripts/spikeglx_spikeinterface_pipeline_new.py", line 192, in <module>
    write_sorting(
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py", line 1240, in write_sorting
    nwbfile = make_nwbfile_from_metadata(metadata=metadata)
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/nwb_conversion_tools/tools/nwb_helpers.py", line 55, in make_nwbfile_from_metadata
    assert "session_start_time" in nwbfile_kwargs, (
AssertionError: 'session_start_time' was not found in metadata['NWBFile']! Please add the correct start time of the session in ISO8601 format (%Y-%m-%dT%H:%M:%S) to this key of the metadata.
```

**Comment by CodyCBakerPhD** [comment]
Aha! We are now out of SpikeInterface-land and into NWB Conversion Tools (NCT)-land, something I can help with;

right around the time we finished this project we were making `session_start_time` a required property of `write_sorting` and other arguments. I thought we had pinned to the previous version, but I suppose if you're seeing this error that is not the case.

If you want to write a stand-alone file with the spike sorted data, simply pass a field `metadata=dict(NWBFile=dict(session_start_time=some_datetime_object))` into `write_sorting` and this should allow it to be specified.

to make a datetime object, simply call

```python
from datetime import datetime

some_datetime_object = datetime(year, month, day, hour ,minute, second)
```

Now, if adding this to an existing NWBFile to which the raw SpikeGLX recording has been written, this field will be set automatically since it's a part of the SpikeGLX header file.

**Comment by sjvenditto** [comment]
I worked! Next I'll try using 2 sorters, but first I wanted to raise a second issue: when I set the parameter `mode_if_folder_exists="keep"`, it doesn't actually skip the spike sorting which already exists, and then tries to save over the existing folder and runs into an error: 

```
kilosort2 run time 3639.68s
kilosort2 found 323 units
Traceback (most recent call last):
  File "/home/venditto/github/brody-lab-to-nwb/scripts/spikeglx_spikeinterface_pipeline_new.py", line 115, in <module>
    we = si.extract_waveforms(recording_processed, sorting, folder=waveform_folder, max_spikes_per_unit=500, **job_kwargs)
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/core/waveform_extractor.py", line 795, in extract_waveforms
    we = WaveformExtractor.create(recording, sorting, folder, use_relative_path=use_relative_path)
  File "/home/venditto/.conda/envs/si_new/lib/python3.9/site-packages/spikeinterface/core/waveform_extractor.py", line 113, in create
    raise FileExistsError('Folder already exists')
FileExistsError: Folder already exists
```

My thought is this is two separate issues? First is ks2 being called even though a folder for it exists, and the second save issue is from the extract_waveforms function which doesn't check if a folder already exists (or I didn't provide a proper flag to check if a folder exists). Do you have any suggestions so I can append a second sorter result without having to rerun ks2 or delete the existing folders?

**Comment by CodyCBakerPhD** [comment]
Wonderful to hear!

@alejoe91 This one is back to you - perhaps that `mode` option has changed behavior since the last time I messed with it (`keep` used to auto-load results as I recall)

**Comment by alejoe91** [comment]
@sjvenditto Yeahhh!!

So I just looked at the notebook again, and in the cell before the `run_sorters` we remove the `working_dir` no matter what! You can remove that part (`if working_folder.is_dir(): shutil.rmtree(working_folder)`) and then the `keep` should do its job (unless the folder is deleted somewhere else...).

In order to reload the pre-computed waveform extractor, you can use the `load_if_exists=True` argument here:
```
we = si.extract_waveforms(recording_processed, sorting, folder=waveform_folder, load_if_exists=True,
                                            max_spikes_per_unit=500, **job_kwargs)
```

**Comment by CodyCBakerPhD** [comment]
Discussed with @sjvenditto and issue can now be closed.

@sjvenditto If you ever have any other trouble with this or related operations please feel free to raise a new issue
